<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="vprybeha-w7" ignored="0" name="test1" tests="3" failures="1" timestamp="27 Nov 2018 14:44:04 GMT" time="25.795" errors="0">
  <testcase name="First" time="0.236" classname="tests.TestClass"/>
  <testcase name="Second" time="0.004" classname="tests.TestClass">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at tests.TestClass.Second(TestClass.java:31)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- Second -->
  <testcase name="Third" time="0.001" classname="tests.TestClass"/>
</testsuite> <!-- test1 -->
